-- Categories
INSERT INTO CATEGORY (ID, NAME) VALUES (1, 'Guitar');
INSERT INTO CATEGORY (ID, NAME) VALUES (3, 'Percussion');
INSERT INTO CATEGORY (ID, NAME) VALUES (4, 'Harp');
INSERT INTO CATEGORY (ID, NAME) VALUES (5, 'Keyboard');
INSERT INTO CATEGORY (ID, NAME) VALUES (6, 'Horn');
INSERT INTO CATEGORY (ID, NAME) VALUES (7, 'Trombone');
INSERT INTO CATEGORY (ID, NAME) VALUES (8, 'Piano');
-- Insert some tuples for tests
INSERT INTO ITEM (ID, NAME, QUANTITY, CAT_ID) VALUES (S_ITEM.NEXTVAL, 'Acoustic guitars', 3, 1);
INSERT INTO ITEM (ID, NAME, QUANTITY, CAT_ID) VALUES (S_ITEM.NEXTVAL, 'Andean harp', 2, 4);
